version: '3.2'
networks:
  web:
    external: true
  internal:
    external: false
services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    restart: always
    ports:
    - 80:80
    - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik-v2.2.toml:/traefik.toml
      - $PWD/traefik_dynamic.toml:/traefik_dynamic.toml
      - $PWD/acme.json:/acme.json
  jenkins:
    container_name: ccmb-jenkins
    image: williamjds/ccmb-jenkins:latest
    restart: always
    environment:
      # in docker compose the containers are on the same network and can be addressed by their names as hostname: configuration-server
      - CASC_JENKINS_CONFIG=/usr/local/configuration/configuration-as-code.yaml
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - BROWN_ACCOUNT_USER=${BROWN_ACCOUNT_USER}
      - BROWN_ACCOUNT_PASSWORD=${BROWN_ACCOUNT_PASSWORD}
      - GITHUB_ACCOUNT_USER=${GITHUB_ACCOUNT_USER}
      - GITHUB_ACCOUNT_PASSWORD=${GITHUB_ACCOUNT_PASSWORD}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    labels:
      - traefik.http.routers.jenkins.rule=Host(`jenkins.localhost`)
      - traefik.http.routers.jenkins.tls=true
      - traefik.http.routers.jenkins.tls.certresolver=lets-encrypt
      - traefik.docker.network=web
      - traefik.port=8080
      - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto: https"
      - traefik.frontend.headers.SSLRedirect=true
    networks:
      - internal
      - web
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./configuration:/usr/local/configuration
