[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$/dqAVsZm$94knPscmU3F0.uRfuyrj.0"
  ]

[http.routers.api]
  rule = "Host(`monitor.localhost`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"